name: GitHub Actions Demo

on: [push]

jobs:
  setup-deps:
    name: Setup project dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup cache
        uses: ./.github/actions/cache
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [setup-deps]
    steps:
      - uses: actions/checkout@v2
      - name: re-use cache
        uses: ./.github/actions/cache
      - run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [setup-deps]
    steps:
      - uses: actions/checkout@v2
      - name: get branch name
        id: branch_name
        run: echo '::set-output name=BRANCH_NAME::$(git rev-parse --abbrev-ref HEAD)'
      - name: get base commit
        id: base_commit
        run: echo '::set-output name=BASE_COMMIT::$(git merge-base master ${{ steps.branch_name.outputs.BRANCH_NAME }})'
      - run: echo ${{ steps.base_commit.outputs.BASE_COMMIT }}
      - run: yarn test --changedSince c0fea28df7cd138a41cd291caa03c69da8f38db4
      # - run: echo ${{ steps.setup_deps.outputs.MASTER_HASH }}
