name: GitHub Actions Demo

on: [push]

jobs:
  setup-deps:
    name: Setup project dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup cache
        uses: ./.github/actions/cache
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [setup-deps]
    steps:
      - uses: actions/checkout@v2
      - name: re-use cache
        uses: ./.github/actions/cache
      - run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [setup-deps]
    steps:
      # - run: echo ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v2
      - name: re-use cache
        uses: ./.github/actions/cache
      - run: echo ${{ github.token }}
      - run: node ./scripts/index.js
      # - run: echo ${{ github.repository }}
      # - run: yarn test --changedSince ${{ github.event.pull_request.head.sha }}
      # - run: echo ${{ steps.setup_deps.outputs.MASTER_HASH }}
