name: GitHub Actions Demo
on: [push]
jobs:
  setup-deps:
    name: Setup project dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: yarn install
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [setup-deps]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: yarn lint
  yest:
    name: Test
    runs-on: ubuntu-latest
    needs: [setup-deps]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: yarn test
