name: GitHub Actions Demo

on: [push]

jobs:
  setup-deps:
    name: Setup project dependencies
    id: setup_deps
    runs-on: ubuntu-latest
    steps:
      - name: Get master commit hash
        run: echo '::set-output name=MASTER_HASH::$(git rev-parse HEAD)'
      - uses: actions/checkout@v2
      - name: setup cache
        uses: ./.github/actions/cache
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [setup-deps]
    steps:
      - uses: actions/checkout@v2
      - name: re-use cache
        uses: ./.github/actions/cache
      - run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [setup-deps]
    steps:
      - run: echo $(git rev-parse HEAD)
      - run: echo "${{ steps.setup_deps.outputs.MASTER_HASH }}"
