name: GitHub Actions Demo

on: [push]

jobs:
  setup-deps:
    name: Setup project dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup cache
        uses: ./.github/actions/cache
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [setup-deps]
    steps:
      - uses: actions/checkout@v2
      - name: re-use cache
        uses: ./.github/actions/cache
      - run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [setup-deps]
    strategy:
      matrix:
        chunk: [0, 1, 2, 3]
    steps:
      - uses: actions/checkout@v2
      - name: re-use cache
        uses: ./.github/actions/cache
      - run: ./scripts/chunk_tests ${{ matrix.chunk }}
